# Generated by Django 5.2.3 on 2025-07-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumento',
            name='codigo',
        ),
    ]
