# Generated by Django 5.2.3 on 2025-07-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_administrador_cliente_administrador_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='administrador_asignado',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='rol',
            field=models.CharField(help_text='Contador, TI, Tributaria', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut_empresa',
            field=models.CharField(help_text='RUT sin puntos y con guion. ', max_length=12, unique=True),
        ),
    ]
