# Generated by Django 5.2.3 on 2025-07-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_remove_cliente_administrador_asignado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Documentos', to='Portal.cliente')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Portal.tipodocumento')),
            ],
            options={
                'unique_together': {('cliente', 'tipo_documento')},
            },
        ),
        migrations.CreateModel(
            name='ArchivoSubido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m')),
                ('subido_por', models.CharField(choices=[('cliente', 'Cliente'), ('consultora', 'Consultora')], max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='Portal.categoriadocumento')),
            ],
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
