# Generated by Django 5.2.3 on 2025-07-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0004_categoriadocumento_archivosubido_delete_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumento',
            name='codigo',
        ),
    ]
