# Generated by Django 5.2.3 on 2025-07-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0005_remove_tipodocumento_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivosubido',
            options={'ordering': ['correlativo']},
        ),
        migrations.AddField(
            model_name='archivosubido',
            name='correlativo',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='archivosubido',
            unique_together={('categoria', 'correlativo')},
        ),
    ]
